version: "3.8"
services:
  node:
    image: "node:lts-alpine"
    container_name: vue
    user: "node"
    working_dir: /var/www
    environment:
      - NODE_ENV=local
    volumes:
      - ./:/var/www
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    command: "yarn dev --host"